# docker-compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

services:
  paperless-broker:
    image: redis:8
    restart: unless-stopped
    x-machines:
      - YOURHOST(S)

  paperless-db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - /shared/paperlessngx/paperlessng/db2:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: SUPERSTRONGPASSWORD!
    x-machines:
      - YOURHOST(S)

  paperless-webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless-db
      - paperless-broker
      - paperless-gotenberg
      - paperless-tika
    x-ports:
      - paperless.YOURDOMAIN.COM:8000/https
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /shared/paperlessngx/paperlessng/data:/usr/src/paperless/data
      - paperless-paperlessmedia:/usr/src/paperless/media
      - paperless-paperlessexport:/usr/src/paperless/export
      - paperless-paperlessconsume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_DBHOST: paperless-db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBPASS: SUPERSTRONGPASSWORD!
      PAPERLESS_URL: https://paperless.YOURDOMAIN.COM
    x-machines:
      - YOURHOST(S)

  paperless-gotenberg:
    image: thecodingmachine/gotenberg
    restart: unless-stopped
    environment:
      DISABLE_GOOGLE_CHROME: 1
    x-machines:
      - YOURHOST(S)
      
  paperless-tika:
    image: apache/tika
    restart: unless-stopped
    x-machines:
      - YOURHOST(S)

volumes:
  paperless-paperlessmedia:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=YOURIP,nolock,soft"
      device: ":/NFSSERVERPATH"
  paperless-paperlessexport:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=YOURIP,nolock,soft"
      device: ":/NFSSERVERPATH"
  paperless-paperlessconsume:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=YOURIP,nolock,soft"
      device: ":/NFSSERVERPATH"

