# This file tells the 'uc' CLI how to connect to the daemon.
contexts:
  host-cluster:
    connections:
      # Connect to the socat map of the mounted unix socket (see index.ts)
      - tcp: 127.0.0.1:50051
current_context: host-cluster
